version: "3"
services:
  logimodel:
    build: .
    volumes:
      - ./ml_vol:/opt/ml_vol
    ports:
      - 8000:8000
    working_dir: /opt/ModellingLogistic
    command: tail -f /dev/null # keep the container running
    
