version: "3"
services:
  logimodel:
    build: .
    volumes:
      - /pathtodata/ml_vol:/modellingLogistic/ml_vol
    ports:
      - 8000:8000
    working_dir: /modellingLogistic
    command: tail -f /dev/null # keep the container running
    #command: ./train /bash/sh
