#!/usr/bin/env Rscript

library(data.table) # Opted for this, 1. Because its really fast 2. dplyr conflicted with plumber
library(rjson) # for handling json data
library(glue)

# call the preprocessing pipeline 
source("preprocessor.R")

encoded_target <- readRDS("./../model_inputs_outputs/model/artifacts/encoded_target.rds")
df <- preprocessing()

# function to train the model  and save it back into the mounted volume
#lets_train <- function(df,encoded_target){

  theModel <- glm(encoded_target ~ ., family = binomial(link = "logit"), data = df)

  # save the model into the artifacts folder in the attached volume.
  saveRDS(theModel, "./../model_inputs_outputs/model/artifacts/predictor.rds")

#}

# calling the model
#glmModel <- lets_train(df=df, encoded_target = encoded_target)

